name: build

on:
  push:
  pull_request:

env:
  # USE UTF8 ENCODING. SHOULD BE DEFAULT, BUT THIS IS INSURANCE AGAINST FUTURE CHANGES
  PYTHONIOENCODING: UTF8

jobs:
  build_linux:
    name: build on linux
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: install conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: '3.7'

      - name: install dependencies
        run: |
          conda install astropy
          conda install pytest
          conda install pytest-astropy

      - name: run build
        run: |
          python setup.py test --coverage
          python stup.py egg_info

      - name: run compliance checks
        run: |
          pycodestyle caltest --count

  build_docs:
    name: build docs
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: install conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          channels: http://ssb.stsci.edu/astroconda
          python-version: '3.7'

      - name: install dependencies
        run: |
          conda install astropy
          conda install sphinx
          conda install stsci_sphinx_theme

      - name: run build
        run: |
          python setup.py build_docs -w

  build_osx:
    name: build on osx
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: install conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: '3.7'

      - name: install dependencies
        run: |
          conda install astropy
          conda install pytest
          conda install pytest-astropy

      - name: run build
        run: |
          python setup.py test
